### ISSUE TITLE
No S3 Bucket Textbox or Demos

### ISSUE THREAD

**Issue by dack-fe** [fpga-open-speech-tools/autogen_webapp#2]
With commit f27c9d8, there is no textbox to enter the S3 Bucket Name
![no_s3_bucket](https://user-images.githubusercontent.com/53094583/97059433-a8960080-154d-11eb-885d-afa8dffd648d.PNG)

**Comment by FE-Sobrero** [comment]
I am guessing that the typescript was not recompiled, and as a result, you're running an old JavaScript from a prior build. I can walk you through recompiling. The typescript. 

This will need to be added to the publish step.

**Comment by dack-fe** [comment]
The current build has a text box for a different bucket but there is still an error with the CORS Policy.  @fe-wickham and I will investigate it tomorrow.

`Access to fetch at 'https://fpga-open-speech-tools-demos.s3.us-west-2.amazonaws.com/' from origin 'http://192.168.0.130:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by fe-wickham** [comment]
> The current build has a text box for a different bucket but there is still an error with the CORS Policy. @fe-wickham and I will investigate it tomorrow.

I have resolved the CORS Policy issues by updating the buckets in S3. The S3 bucket selector does appear to be working

**Comment by dack-fe** [comment]
Fixed with Utils S3 Template
